### PR TITLE
Feature: use permanent location id over place name

### PR DESCRIPTION
**Pull request by rpk506**
Couple of updates to the code here

- generate URL hashes from location id rather than location name
- update template URLs to use stable Pattern Library path instead of specific version

### CODE REVIEW

**Comment by chris5marsh** [comment]
Are we sure that the result rank in Funnelback is a permanent number for the locations? In Funnelback you've added:

```
"locationid": "locid-${s.result.rank?c}"
````

What happens when we add more locations or move things around in the Google Sheet?

You can see the test default results layout (simple.ftl) here: https://york.funnelback.co.uk/s/search.html?collection=york-uni-campusmap&form=simple&profile=_default_preview&query=%21padrenullquery

I've added a line that says what rank it is - could we test it by moving or renaming the locations and see if it affects the rankings?

**Comment by rpk506** [comment]
My gut feeling is that it probably _will_ change the rankings if we move it around, but I couldn't think of a better way to give them a more permanent ID value. If it was just the Google Sheet, then we could add a field in there, but doesn't it draw from multiple sources (Rooms API, Printers, GSheet)? 

That's the tricky part, merging the data and generating a unique, assigned ID.

**Comment by rpk506** [comment]
As an update to this, not much has changed in the code, but I've pulled in a new location id from Funnelback that should solve this. It's autogenerated from the Rooms API and within the Google Sheet, I've set a formula up to use part of the category name and the row number, so the id should be both unique and not-subject to change

**Pull request merged**
